### ISSUE TITLE
No aparecen las url en las referencias bibiográficas

### ISSUE THREAD

**Issue by ubutfgm** [ubutfgm/plantillaLatex#12]
Una nueva versión de la plantilla está en camino. Por el momento se puede solucionar ese fallo cambiando 

\bibliographystyle{plain}
\bibliography{bibliografia}

por 
\bibliographystyle{IEEEtran}
\bibliography{IEEEabrv,bibliografia}

en el fichero memoria.tex

**Comment by Alberto-Vivar** [comment]
He tenido algún problema al no poder compilar el documento al cambiar a ese estilo de bibliografía, me ponía que no podía encontrar **IEEEtran.bst**.

> I couldn't open style file IEEEtran.bst
> ---line 42 of file memoria.aux
>  : \bibstyle{IEEEtran
>  :                   }
I'm skipping whatever remains of this command

En mi caso ha sido utilizando TeXstudio, y lo he solucionado actualizando la herramienta tlmgr (que por lo visto lo necesitaba) mediante:
`$ sudo tlmgr update --self`
Y después instalando el paquete de forma manual:
`$ sudo tlmgr install IEEEtran`

Por si a alguien le sirve.

**Comment by joseFranciscoDiez** [comment]
Ese fichero se puede encontrar en 

https://www.ctan.org/tex-archive/macros/latex/contrib/IEEEtran/bibtex

Habría que descargar el fichero y dejarlo a la misma altura que memoria.tex

**Comment by ubutfgm** [comment]
Se debe utilizar ```howpublished``` en vez de ```url```. Se ha cambiado la plantilla para que se pueda ver. Ejemplo

```latex
@misc{ wiki:latex,
       author = "Wikipedia",
       title = "LaTeX --- Wikipedia{,} La enciclopedia libre",
       year = "2015",
       howpublished = {\url{https://es.wikipedia.org/w/index.php?title=LaTeX&oldid=84209252}},
       note = "[Internet; descargado 30-septiembre-2015]"
}
```
