### ISSUE TITLE
Control de viudas y húerfanas

### ISSUE THREAD

**Issue by alvarag** [ubutfgm/plantillaLatex#14]
Se debería controlar tanto en la memoria como en los anexos.

**Comment by cgosorio** [comment]
La clase memoir se supone que está diseñada para tener en cuenta un montón de aspectos del diseño de página, no me atrevo a hacer cambios en la plantilla. No obstante, dejo este enlace, donde se indica algunos de los cambios que podrían hacerse para cambiar los parámetros que controlan estos tipos de patologías.

http://edilatex.blogspot.com.es/2011/06/viudas-y-huerfanas.html
