### ISSUE TITLE
Eliminar ficheros temporales

### ISSUE THREAD

**Issue by clopezno** [ubutfgm/plantillaLatex#3]

**Comment by davidmigloz** [comment]
https://www.gitignore.io/api/latex%2Ctex

**Comment by clopezno** [comment]
Gracias David se lo paso a @joseFranciscoDiez que es el responsable de mantener este repositorio de la documentación de Latex.
Primero para que los eliminine y luego para que aplique el fichero de configuración que nos indicas.

**Comment by davidmigloz** [comment]
Perfecto 😉

**Comment by ubutfgm** [comment]
Muchas gracias.
